### ISSUE TITLE
VS2008 compatibility?

### ISSUE THREAD

**Issue by robi-wan** [uaf/uaf#29]
We use this great library with Python 2.7.5 under Windows XP.

But sometimes we see ugly crashes which we weren't able to debug - today I saw it crash. The error dialog mentioned the file 'msvcr100.dll' - this reminded me that there is a recommendation (or necessity) to compile native python extensions with the same compiler as the python version - for Python 2.7.5 under Windows this means Visual Studio 2008: https://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows/11405614#11405614

I worked with uaf tag v1.5: I installed current versions of SWIG (3.0.2), CMAKE (3.0.0) and OPC-UA (1.3.3 for VS2008) and generated the VS project files.
When compiling there were a lot of errors because VS 2008 is missing the 'stdint.h'

I took the stdint.h file provided with Visual Studio 2010 and tweaked it because there were warnings about some redefined macros (WCHAR_MIN).

Using this tweaked stdint.h helped just partially - there were still a lot of build errors: 
e.g. `error C2039: 'at' : is not a member of 'std::map<_Kty,_Ty>'`. Full log: 
https://gist.github.com/1e9a90c0a71b9cb6ae05

Is support for Visual Studio 2008 possible/planned or out of scope?
